name: BasePlugin
version: '${project.version}'
main: com.gmail.murcisluis.base.spigot.plugin.BasePlugin
api-version: 1.13
authors: [ Murcis_Luis ]
description: A base plugin
softdepend:
  - PlaceholderAPI

permissions:
  bp.admin:
    description: Allow player to use admin commands
  bp.use:
    default: true
    description: Allow player to use default permissions