name: '${displayName}'
version: '${version}'
main: com.gmail.murcisluis.base.spigot.plugin.BaseSpigotPlugin
api-version: 1.16
authors: [ Murcis_Luis ]
description: A base plugin
depend:
  - MythicMobs
softdepend:
  - PlaceholderAPI
